### ISSUE TITLE
Errors keep occurring.

### ISSUE THREAD

**Issue by halhns** [paissaheavyindustries/Triggernometry#108]
It is fine to use but keeps giving me errors all the time.
Since this is a Japanese-language environment, Japanese is included.

```
System.InvalidCastException - 型 'Triggernometry.Folder' のオブジェクトを型 'Triggernometry.RepositoryFolder' にキャストできません。
   場所 Triggernometry.CustomControls.UserInterface.timer1_Tick(Object sender, EventArgs e)
   場所 System.Windows.Forms.Timer.OnTick(EventArgs e)
   場所 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Triggernometry.CustomControls.UserInterface, TriggernometryPlugin, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null
```

**Comment by MnFeN** [comment]
Is this error reproducable without the JP translation?

**Comment by halhns** [comment]
It stopped happening when I set the language setting back to default. Thanks.
I was using this one, but I guess it was too old.
https://github.com/griefnote/Triggernometry/blob/master/Translations/Japanese.triglations.xml
