### ISSUE TITLE
Could not load file or assembly 'ShapDX.Direct2D1,Version=4.2.0.0, Culture=neutral

### ISSUE THREAD

**Issue by 01yt01cs89** [paissaheavyindustries/Triggernometry#11]
I don't know what I'm missing but Triggernometry pluging dont work for me because this error,I had unblock and enable Run as administrator

**Comment by 01yt01cs89** [comment]
![Error](https://user-images.githubusercontent.com/25095674/64739216-751a2300-d4bf-11e9-8389-3dd4a3324881.png)

**Comment by 01yt01cs89** [comment]
![Error2](https://user-images.githubusercontent.com/25095674/64739222-7d725e00-d4bf-11e9-9153-f2de8f2ad17c.png)

**Comment by 01yt01cs89** [comment]
![Error](https://user-images.githubusercontent.com/25095674/64739396-fa9dd300-d4bf-11e9-97ec-898295ec08e3.png)

**Comment by 01yt01cs89** [comment]
![Error2](https://user-images.githubusercontent.com/25095674/64739408-ff628700-d4bf-11e9-8b93-17a18d381a58.png)

**Comment by Aho-Senpai** [comment]
If only ppl could learn to read the README files ...

**Comment by Zeffuro** [comment]
Should probably update the wiki with this issue that says READ THE README 

-_-

**Comment by Aho-Senpai** [comment]
Or, you could use that thing called "brain"

**Comment by 01yt01cs89** [comment]
Ty for help:< not good at this kinda stuffs
