### ISSUE TITLE
Feature Request: Add option to OBS action type to add Chapter for hybrid mp4

### ISSUE THREAD

**Issue by Akurosia** [paissaheavyindustries/Triggernometry#112]
With the latest OBS a feature for fragmented mp4 was released.
I would like to have the option to add a chapter on a trigger (makes it easier to find parts in the recording etc) for a hybrid  mp4

**Comment by MnFeN** [comment]
You can try to use this JSON:
```json
{
  "op": 6,
  "d": {
    "requestType": "CreateRecordChapter",
    "requestId": "",
    "requestData": {
      "chapterName": "Your Chapter Name"
    }
  }
}
```

![image](https://github.com/user-attachments/assets/859285b0-70ac-4852-b925-9636e76b7e0e)

(make sure the chapter name does not contain unescaped special characters)

**Comment by Akurosia** [comment]
Thanks, worked like a charm
