### ISSUE TITLE
FFXIV crashes with ACT turned on with Triggernometry

### ISSUE THREAD

**Issue by holdonL** [paissaheavyindustries/Triggernometry#13]
Guys, need some help!

**Comment by Aho-Senpai** [comment]
you are gonna need to give us a whole lot more info that just "it crashes"
have you installed trig correctly ? ACT correctly ?
when does it crash ?
where's your crash report ?
ppl can't just guess it

**Comment by holdonL** [comment]
It crashes mostly in dungeons, had lots of crashes on E2S.
It gives me this message when crashes, sometimes no message at all.
![Screenshot_1](https://user-images.githubusercontent.com/13774389/66255732-d320ea00-e78f-11e9-9234-6dab6694c2fa.png)
Installed Act and Triggernometry correctly, it works as should. Added to exceptions of antivirus + deactivated firewall.
Where can I get crash report?
I've been playing with ACT for a while it was okay but then installed Trig and after a couple of days the game started to crash after a couple of boss pulls. Without ACT no crashes works fine.

System: 

- Windows 10 with the latest updates
- Intel i5 3570k OC 4.6GHz
- Nvidia 1080 Strix (latest driver)
- 16Gb Memory

**Comment by paissaheavyindustries** [comment]
I haven't been able to replicate the issue. Would you be able to try disabling hardware acceleration, and if that helps, can you let me know exactly what triggers you are using?

**Comment by paissaheavyindustries** [comment]
stale issue
