### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Chrisnetika** [paissaheavyindustries/Triggernometry#20]
2019-12-29 04:54:49.763	Error	Version update check failed: The request was aborted: Could not create SSL/TLS secure channel.

Just set it up today along with ACT
keeps showing up in logs

**Comment by paissaheavyindustries** [comment]
That's a Windows thing, you will need at least framework 4.6 for newer HTTPS connections to work.

**Comment by Chrisnetika** [comment]
I am using framework 4.8 tho :(
