### ISSUE TITLE
Exceptions during RealPlugin.InitPlugin are not logged properly

### ISSUE THREAD

**Issue by valarnin** [paissaheavyindustries/Triggernometry#25]
If an exception occurs during `RealPlugin.InitPlugin` its message is assigned to the plugin label in ACT but the actual exception (with stack trace) is never logged anywhere:
https://github.com/paissaheavyindustries/Triggernometry/blob/master/Source/Triggernometry/RealPlugin.cs#L1905

**Comment by paissaheavyindustries** [comment]
Will be popping up as a tray slider (with copy to clipboard) in the next one
