### ISSUE TITLE
Suggestion: Reproduce what Special Spell Timers does/did

### ISSUE THREAD

**Issue by Krojack** [paissaheavyindustries/Triggernometry#27]
I loved the Special Spell Timers when it would work for ACT but I've had a very hard time trying to get help as it's always crashing my ACT now.  Also it comes with a LOT of other features that kinda bloat the plugin now.

Would it be possible to add something to this plugin to do the same thing?  I would assume it would be similar to an Aure Operation but also include a progress bar that you can either have fill-up or empty depending on option.

Here are some examples if what it looks like:

https://i.imgur.com/sdjnzJh.gifv
https://i.imgur.com/du65DTh.gifv

https://i.imgur.com/Tvqzf7d.jpg
https://i.imgur.com/oBAdCfm.jpg

**Comment by Aho-Senpai** [comment]
You can already do that if you want, how is this a "suggestion" or "issue" ?
Sure it's more work to set it up and make it look good, but you CAN do it if you want.

**Comment by Krojack** [comment]
It's a lot of various setting.  I'm looking for 1 single action that can add the icon, a timer bar and maybe a sound when timer reaches 0.  In short, a much simplified way to create these.

I also don't see anyway to make a timer bar like in the first example.

**Comment by Aho-Senpai** [comment]
You have the options and abilities to do it. if you want a "plug and play" solution, this is not what this is for.
And you CAN make a "timer bar".

**Comment by Krojack** [comment]
Sorry I just don't see anything under Action Type for a timer bar nor do I see anything on the wiki or examples for them.
