### ISSUE TITLE
Disabling "all" remote triggers does not work

### ISSUE THREAD

**Issue by mrdregan** [paissaheavyindustries/Triggernometry#28]
If you want to disable remote triggers, you would assume that this:
![grafik](https://user-images.githubusercontent.com/8269994/82702649-af54da80-9c72-11ea-849c-bd61cac04f86.png)
disables them. It doesn't though.

For instance:
![grafik](https://user-images.githubusercontent.com/8269994/82702673-baa80600-9c72-11ea-997a-c36c31a0981b.png)
Would still make the callouts for Aho's Jobs + Raids. When I disable for instance the Jobs repository aswell, then it will stop triggering the job triggers.

Version 1.1.3.1

**Comment by paissaheavyindustries** [comment]
I have not been able to reproduce this issue, it appears to works as expected for me.
