### ISSUE TITLE
Allow zone locking via zone ID

### ISSUE THREAD

**Issue by ayaliz** [paissaheavyindustries/Triggernometry#49]
By zone ID I mean the number shown in the network version of line type 01 as shown here with 337 for TEA:
01|2020-07-21T17:47:26.6590000+02:00|377|The Epic of Alexander (Ultimate)|
If there's only some kind of other zone specific ID you can pull from the parsing plugin that's fine too as long as there's a way to figure out what it should be for each zone.

**Comment by paissaheavyindustries** [comment]
1.1.3.5
