### ISSUE TITLE
Unable to get current CP and current GP values

### ISSUE THREAD

**Issue by PickleTicklewithnospace** [paissaheavyindustries/Triggernometry#55]
Using `_ffxivparty[1].currentcp` returns 0 instead of the correct current cp or current gp value.

**Comment by Aho-Senpai** [comment]
Can you provide a bit more information ? what version does this happen on ?

**Comment by paissaheavyindustries** [comment]
It's an issue in the ffxiv act plugin, currently GP values are going into CP fields, and CP values aren't going anywhere. Ravahn is aware and looks into it when he has time.
