### ISSUE TITLE
The numeric parser doesn't recognize negative numbers after commas correctly

### ISSUE THREAD

**Issue by Leonerdo5** [paissaheavyindustries/Triggernometry#56]
I was trying to using a numeric expression similar to `${numeric: and(${var:x} > 0, ${var:x} < 15) }` where x was a negative number. After substituting, the expression reads `and(-1 > 0, -1 < 15)`, which breaks the parser.

The second negative number is instead treated as an operator and a positive number (assuming I'm reading the source code correctly for the Lexer).

**Comment by paissaheavyindustries** [comment]
fixed in 1.1.6.0
