### ISSUE TITLE
Table Values can't be retrieved in beta 5

### ISSUE THREAD

**Issue by FrUct1s** [paissaheavyindustries/Triggernometry#57]
Can't seem to be able to retrieve table vars
Testtrigger: `Active Text Aura`
Text to Display: `Number: ${tvar:Test[3][2]}`
Text Aura Output:` Number: `
Triggernometry_1_1_4_0_b5

Table value is set in view state - also tried a different table with values and a Repo trigger that retrieves tvar for X & Y values for image auras, none work for me atm, probably a trig beta bug

**Comment by paissaheavyindustries** [comment]
sorted
