### ISSUE TITLE
build instructions for triggernometry please!

### ISSUE THREAD

**Issue by MyTechnoHunter** [paissaheavyindustries/Triggernometry#62]
cloning the repo in visual studio and trying to build fails with packages unable to download (forcibly closed for things like sharpdx and such..

Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project TriggernometryPlugin: Unable to find version '4.5.0' of package 'Microsoft.CSharp'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Microsoft.CSharp.4.5.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host
. Please see Error List window for detailed warnings and errors.		

anything you can mention on how to get it set to build?

thanks in advance
Techno

**Comment by mikusHusbando** [comment]
I just succeeded in loading the project with .NET framework 4.5 without having to retarget the application.
From a clean Win10 install with nothing but all updates done, I went and installed VS 2022 community edition. After that finished I downloaded the package https://www.nuget.org/packages/microsoft.netframework.referenceassemblies.net45 and opened it as a ZIP file. Copy the contents of the build/.NETFramework/v4.5 files into C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5 and overwrite existing files. It no longer asks you to retarget the application when opening up the app. Hope it helps

**Comment by s1ryx** [comment]
Deleted the previous comment as I got it to work without modifying VS-owned files.

Download VS 2022 and select .NET desktop development tools
Additionally check the development tools for 4.6.2-{...} in the optionals tab.
Install ACT on your machine if not present.

When first opening, VS will ask you to either retarget, download 4.5 or do nothing. Choose the last option.
In both project files, change target framework version from V4.5 to V4.6.2 and reload them with dependencies.

Build the TriggernometryProxy plugin and copy the Triggernometry.dll from ~/Source/Repos/Triggernometry/Source/TriggernometryProxy/bin/Debug directory and load it into ACT

**Comment by paissaheavyindustries** [comment]
This was a problem with Trig was still using net 4.5, and ACT had updated to 4.6. Trig was updated to 4.6 as well so this issue resolved itself.
