### ISSUE TITLE
Triggernometry does not work

### ISSUE THREAD

**Issue by KnightPeink** [paissaheavyindustries/Triggernometry#66]
2022-03-17 13:24:51.845	Error	由于下列异常，无法监听FFXIV网络事件：No plugin instance available

**Comment by Aho-Senpai** [comment]
`由于下列异常，无法监听FFXIV网络事件` > `Unable to listen to FFXIV network events due to the following exception`  
You NEED to have FFXIV plugin Installed and Enabled.

**Comment by MyTechnoHunter** [comment]
that and make SURE you have the latest trigg.. the ffxiv plugin changed how it called itself a bit ago.. so older trigg versions WONT see it

**Comment by paissaheavyindustries** [comment]
What they said - make sure you have the FFXIV parsing plugin from Ravahn installed, and also make sure it's the latest version.
