### ISSUE TITLE
the random function description is not correct in the FAQ

### ISSUE THREAD

**Issue by MnFeN** [paissaheavyindustries/Triggernometry#70]
> random(x, y) = random integer between x and y (both inclusive)

The function does not include y: 
_e.g._ random(1,2) always = 1

**Comment by paissaheavyindustries** [comment]
corrected

**Comment by MnFeN** [comment]
> corrected

Hi, here is another typo:

> ${string:xxx} = will cause "xxx" to be evaluated as a **_numeric_** expression and then substituted
