### ISSUE TITLE
Persistent Variable "FloppyDisk" resets to off in some actions when you edit/view them

### ISSUE THREAD

**Issue by FrUct1s** [paissaheavyindustries/Triggernometry#72]
Hard to explain. I'll try.

Whenever you Edit/open the action "Generic JSON operation" the persistent variable "FloppyDisk" icon resets to off/grey.

Same with "Scalar variable operation" -> "Query variable with JSONPath and store list value". although it retains the FloppyDisk on "Scalar variable name" but it loses/resets it on "Target variable name".
![persistentvariable](https://user-images.githubusercontent.com/58904408/175128617-0a043fa1-ff20-4b43-851b-62f929317b97.jpg)

**Comment by FrUct1s** [comment]
I just realisied you don't even need to open the action.

As soon as you open the trigger without touching any of the actions with persisent variables and save the trigger they still reset to off.

**Comment by Makar8000** [comment]
#73 will fix this particular issue. Were there any other instances where the action settings get reset, or was it just this specific persist ("floppy disk") status for "Target variable name"?

**Comment by FrUct1s** [comment]
I noticed it on following two actions and only this setting with the floppy disk:

"Generic JSON operation"
"Scalar variable operation" -> "Query variable with JSONPath and store list value". although it retains the FloppyDisk on "Scalar variable name" but it loses/resets it on "Target variable name".

Thank you for checking

**Comment by Makar8000** [comment]
Updated the PR to include the fix for Generic JSON operation as well
