### ISSUE TITLE
Party List Order currently sorts by Alphabetical for Duplicate Classes. Should be Game ID DESC.

### ISSUE THREAD

**Issue by DJFarr** [paissaheavyindustries/Triggernometry#9]
Triggernometry currently Sorts the Party list according to alphabetical order if there are multiple players of the same class.

After some testing and observation, that game appears to sort these players according to their in-game ID in Descending order.

Some arrows are wrong but the numbers don't lie.

![2019-09-05 23_58_24-Greenshot - Copy](https://user-images.githubusercontent.com/16067714/64354831-50492a00-d03f-11e9-8682-136b2ad31ea6.png)
![2019-09-05 23_38_49-Greenshot](https://user-images.githubusercontent.com/16067714/64354842-563f0b00-d03f-11e9-9cff-27a38d8b51b4.png)
![2019-09-05 23_16_09-Greenshot](https://user-images.githubusercontent.com/16067714/64354843-563f0b00-d03f-11e9-8ba6-abcd45eeb03b.png)
![2019-09-05 23_21_01-Greenshot](https://user-images.githubusercontent.com/16067714/64354844-56d7a180-d03f-11e9-8db5-42c37d95b21f.png)
![2019-09-05 23_22_47-Greenshot](https://user-images.githubusercontent.com/16067714/64354846-56d7a180-d03f-11e9-8464-eb2e2c623de9.png)
![2019-09-05 23_32_53-Greenshot](https://user-images.githubusercontent.com/16067714/64354848-56d7a180-d03f-11e9-9d78-15554abe4912.png)
![2019-09-05 23_35_29-Greenshot](https://user-images.githubusercontent.com/16067714/64354850-56d7a180-d03f-11e9-97b5-3e0335e42712.png)

**Comment by paissaheavyindustries** [comment]
Fixed in the next one
