### ISSUE TITLE
Text Aura Font (text outline color) not working

### ISSUE THREAD

**Issue by FrUct1s** [paissaheavyindustries/Triggernometry#95]
Maybe related to the Background color conversion issue?

Easy Test: Set Font color and Background color White  - set Outline color to anything but white
![image](https://github.com/paissaheavyindustries/Triggernometry/assets/58904408/ca1b1d68-af6f-44cc-a730-251248985ecb)
![image](https://github.com/paissaheavyindustries/Triggernometry/assets/58904408/2b0709d5-70de-4cf4-a4c5-730343458a4a)

**Comment by MnFeN** [comment]
Edit: we missed the outline option... nothing wrong with it

![image](https://github.com/paissaheavyindustries/Triggernometry/assets/85232361/6e624bdd-8955-4e86-8cf8-46bb1a2bf28e)

**Comment by paissaheavyindustries** [comment]
should be fixed
